project:
  type: book

book:
  title: "LiDAR Forestry"
  author: 
    - name: Seamus Murphy
      url: https://scholar.google.com/citations?hl=en&user=jDGq9I4AAAAJ
      orcid: 0000-0002-1792-0351 
      email: seamusrobertmurphy@gmail.com
  date: today
  favicon: ./assets/PNG/favicon.png
  open-graph: true 
  page-footer:
    left: "[Source](https://github.com/seamusrobertmurphy/lidar-forestry)"
  
  site-url: https://seamusrobertmurphy.quarto.pub/lidar-forestry/
  repo-url: https://github.com/seamusrobertmurphy/lidar-forestry
  repo-branch: main
  repo-actions: [edit, issue]

  tools:
    - icon: linkedin
      href: https://linkedin.com/in/seamusrobertmurphy
      text: "LinkedIn"
    - icon: file-earmark-pdf
      href: https://drive.google.com/uc?export=download&id=13YLhsRCAMMHQw-jd2SJdaRJH9udBGytP
      text: "Resume"
    - icon: mortarboard
      href: https://scholar.google.com/citations?hl=en&user=jDGq9I4AAAAJ
      text: "Scholar"

  chapters:
    - index.qmd
    - point-cloud/index.qmd
    - stem-detect/index.qmd
    - canopy-height/index.qmd
    - biomass-model/index.qmd

  appendices:
    - resources/index.qmd

bibliography: references.bib
csl: apa.csl
citeproc: false  

filters:
  - quarto  
  - section-bibliographies

reference-section-title: References

section-bibliographies:
  level: 1
  minlevel: 1  
  
sidebar:
    title: "LiDAR Forestry Tools"
    search: true
    style: "docked"
    collapse-level: 2

format:
  html:
    number-depth: 2
    theme: 
      - styles.scss
      - default
    code-fold: false
    code-summary: "Code"
    code-tools: true
    code-link: true
    knitr:
      opts_chunk:
        out.width: 100%
        R.options:
          width: 68

engine: knitr

knitr:
  opts_chunk: 
    collapse: true
    comment: "#" 
    R.options:
      knitr.graphics.auto_pdf: true
      dplyr.print_min: 6
      dplyr.print_max: 6
      stars.crs: 17
      digits: 3
